### PR TITLE
Custom product button label

### PR DESCRIPTION
**Pull request by amadornimbis**
Adding a purchase_button_label field to the RichProductMixin.

This new field allows you to customize the purchase button text on a
product-by-product basis. A new migration has also been created for this
change.

### CODE REVIEW

**Comment by amadornimbis** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;3UyTJkYG&#x2F;93-1-allow-products-to-change-button-label-text"> (1) Allow products to change button label text</a>

**Comment by cworth-gh** [comment]
This one looks good to me. I looked hard and all I could find was a single letter typo in the 4th commit message, ("unit tests now tests"---one or the other of "tests" should be "test"). But obviously, that's not important to fix.

**Comment by shaunbrady** [comment]
One comment; looks good.

**Comment by mliudev** [comment]
Looks good to me

**Pull request merged**
